AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  writeToS3
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  WriteToS3Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: writeToS3/
      Handler: writeToS3.writeToS3Handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        WriteToS3:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /writeToS3
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WriteToS3Api:
    Description: "API Gateway endpoint URL for Prod stage for Write To S3 function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/writeToS3/"
  WriteToS3Function:
    Description: "Write To S3 Lambda Function ARN"
    Value: !GetAtt WriteToS3Function.Arn
  WriteToS3FunctionIamRole:
    Description: "Implicit IAM Role created for Write To S3 function"
    Value: !GetAtt WriteToS3FunctionRole.Arn
